spring:
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
server:
  address: 0.0.0.0
  port: 8101
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000